# Generated by Django 4.2.7 on 2023-12-03 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('codigo_barra', models.CharField(max_length=50)),
                ('fecha_contable', models.DateField()),
                ('fecha_adquisicion', models.DateField()),
                ('vida_util_total', models.IntegerField()),
                ('vida_util_restante', models.IntegerField()),
                ('costo_alta', models.IntegerField()),
                ('valor_neto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('piso', models.IntegerField()),
                ('edificio', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('unidad_inacap', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento_activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProject.activo')),
                ('id_tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProject.tipo_activo')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='id_bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProject.bodega'),
        ),
        migrations.AddField(
            model_name='activo',
            name='id_tipo_activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProject.tipo_activo'),
        ),
    ]
