# Generated by Django 4.2.7 on 2023-12-13 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('piso', models.IntegerField()),
                ('edificio', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_inacap', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('Defau', 'Termino defaul, no usar o hubo un error'), ('AD_ac', 'Se agrego un activo al inventario'), ('ED_ac', 'Se actualizo un activo en inventario'), ('DE_ac', 'Se elimino un activo del inventario'), ('AD_bo', 'Se registro una nueva bodega'), ('ED_bo', 'Se actualizaron datos de una bodega'), ('DE_bo', 'Se elimino una bodega del registro'), ('AD_ta', 'Se agrego un nuevo tipo de activo'), ('ED_ta', 'Se actualizaron datos de un tipo de activo'), ('DE_ta', 'Se elimino un tipo de activo del registro'), ('AD_ab', 'Se agrego un activo a una bodega'), ('ED_ab', 'Se movio un activo de una bodega a otra bodega'), ('DE_ab', 'Se quito un activo de una bodega')], default='Defau', max_length=5)),
                ('nombre_activo', models.CharField(max_length=50, null=True)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_bodega', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('codigo_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_contable', models.DateField()),
                ('fecha_adquisicion', models.DateField()),
                ('fecha_descontinuacion', models.DateField(blank=True, null=True)),
                ('costo_alta', models.IntegerField()),
                ('valor_neto', models.IntegerField()),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProject.bodega')),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appProject.tipo_activo')),
            ],
        ),
    ]
